In [1]:
#import dependencies
import os
import csv
import pandas as pd

In [2]:
# Path to collect data from the Resources folder

#1 - Death Counts for Infections - Influenza, Pnuemonia, COVID-19

file_path = os.path.join('..', 'References', 'Death_Counts_for_infections_Influenza__Pneumonia__and_COVID-19.csv')

# Import the Death_Counts_for_infections_Influenza__Pneumonia__and_COVID-19.csv file as a DataFrame
death_counts_df=pd.read_csv(file_path)

death_counts_df.head(5)

,Data As Of,Start Week,End Week,MMWRyear,MMWRweek,Group,Indicator,Jurisdiction,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,All Ages,0.0,58486.0,3789.0,478.0,4267.0,4267.0,NaN
1,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,0-17 years,0.0,652.0,12.0,16.0,28.0,28.0,NaN
2,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,18-64 years,0.0,13994.0,700.0,184.0,884.0,884.0,NaN
3,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,65+ years,0.0,43840.0,3077.0,278.0,3355.0,3355.0,NaN
4,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,All Ages,0.0,1055.0,55.0,16.0,71.0,71.0,NaN

In [3]:
#Summary Statistics

death_counts_df.describe()

## shows cases where cells are blank
## investigate: 
######## where One or more data cells have counts between 1-9
######## and have been suppressed in accordance with NCHS confidentiality standards.

###Cleansing Assumption: ???

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
count,9828.0,9828.000000,8204.000000,8809.000000,8064.000000,7571.000000,8044.000000,8193.000000
mean,2020.0,24.000000,154.804851,1589.796912,161.552951,4.497556,166.974515,248.267668
std,0.0,11.255201,719.894200,5320.650575,582.938225,29.227457,599.098948,965.397469
min,2020.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.0,14.000000,0.000000,88.000000,0.000000,0.000000,0.000000,10.000000
50%,2020.0,24.000000,11.000000,388.000000,32.000000,0.000000,34.000000,43.000000
75%,2020.0,34.000000,70.000000,1204.000000,104.250000,0.000000,109.000000,151.000000
max,2020.0,43.000000,17059.000000,78793.000000,11960.000000,653.000000,12432.000000,21211.000000

In [4]:
# Finding how many unique Jurisdictions are provided
death_counts_df["Jurisdiction"].unique() ##value_counts()

####  HHS Regions: https://www.hhs.gov/about/agencies/iea/regional-offices/index.html
### exclude since we cannot aggregate with other datasources

array(['United States', 'Alabama', 'Alaska', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'New York City', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming', 'HHS Region 1', 'HHS Region 2', 'HHS Region 3',
       'HHS Region 4', 'HHS Region 5', 'HHS Region 6', 'HHS Region 7',
       'HHS Region 8', 'HHS Region 9', 'HHS Region 10'], dtype=object)

In [5]:
##remove HHS Regions from data
clean_df = death_counts_df[~death_counts_df["Jurisdiction"].str.contains('HHS Region')] 
clean_df["Jurisdiction"].unique()

array(['United States', 'Alabama', 'Alaska', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'New York City', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming'], dtype=object)

In [6]:
clean_df.describe()

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
count,8268.0,8268.000000,6805.000000,7256.000000,6707.000000,6477.000000,6699.000000,6868.000000
mean,2020.0,24.000000,124.180602,1286.515711,129.218279,3.373784,133.406926,197.243157
std,0.0,11.255309,723.024378,5604.098882,601.657585,29.427364,617.890254,983.893028
min,2020.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.0,14.000000,0.000000,74.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.0,24.000000,0.000000,306.500000,25.000000,0.000000,26.000000,33.000000
75%,2020.0,34.000000,50.000000,904.250000,77.000000,0.000000,80.000000,106.000000
max,2020.0,43.000000,17059.000000,78793.000000,11960.000000,653.000000,12432.000000,21211.000000

In [7]:
### Remove the All Ages category from the "Age Group" Column
clean_df2=clean_df[clean_df["Age Group"]!="All Ages"]

### Remove the United States category from the "Jurisdiction" Column
clean_df2=clean_df2[clean_df2["Jurisdiction"]!="United States"]
clean_df2

,Data As Of,Start Week,End Week,MMWRyear,MMWRweek,Group,Indicator,Jurisdiction,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
5,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,0-17 years,0.0,24.0,NaN,NaN,NaN,NaN,One or more data cells have counts between 1-9...
6,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,18-64 years,0.0,275.0,15.0,NaN,23.0,23.0,One or more data cells have counts between 1-9...
7,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,65+ years,0.0,756.0,39.0,NaN,46.0,46.0,One or more data cells have counts between 1-9...
9,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alaska,0-17 years,0.0,NaN,NaN,NaN,NaN,NaN,One or more data cells have counts between 1-9...
10,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alaska,18-64 years,0.0,29.0,NaN,0.0,NaN,NaN,One or more data cells have counts between 1-9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wisconsin,18-64 years,NaN,89.0,NaN,0.0,NaN,NaN,One or more data cells have counts between 1-9...
9783,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wisconsin,65+ years,53.0,425.0,35.0,0.0,35.0,68.0,NaN
9785,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wyoming,0-17 years,0.0,0.0,0.0,0.0,0.0,0.0,NaN
9786,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wyoming,18-64 years,0.0,NaN,0.0,0.0,0.0,0.0,One or more data cells have counts between 1-9...
9787,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wyoming,65+ years,NaN,39.0,NaN,0.0,NaN,NaN,One or more data cells have counts between 1-9...

In [8]:
#Group by Jurisdiction and Age Group - mean of remaining columns
age_grp1_df=clean_df2.groupby(['Jurisdiction', 'Age Group']).mean()
age_grp1_df
age_grp1_df=age_grp1_df.rename(
    columns= {'COVID-19 Deaths':"Average COVID-19 Deaths",
              'Total Deaths':"Average Total Deaths",
              "Pneumonia Deaths":"Average Pneumonia Deaths",
              "Influenza Deaths":"Average Influenza Deaths",
              "Pneumonia or Influenza":"Average Pneumonia or Influenza",
              "Pneumonia, Influenza, or COVID-19 Deaths":"Average Pneumonia, Influenza, or COVID-19 Deaths"         
            })
age_grp1_df.head(5)

                          MMWRyear  MMWRweek  Average COVID-19 Deaths  \
Jurisdiction Age Group
Alabama      0-17 years       2020        24                 0.000000
             18-64 years      2020        24                24.054054
             65+ years        2020        24                80.342105
Alaska       0-17 years       2020        24                 0.000000
             18-64 years      2020        24                 0.000000

                          Average Total Deaths  Average Pneumonia Deaths  \
Jurisdiction Age Group
Alabama      0-17 years              13.107143                  0.000000
             18-64 years            318.743590                 22.594595
             65+ years              812.076923                 69.512821
Alaska       0-17 years               0.000000                  0.000000
             18-64 years             31.135135                  0.000000

                          Average Influenza Deaths  \
Jurisdiction Age Group
Alabama      0-17 years                   0.000000
             18-64 years                  0.392857
             65+ years                    0.000000
Alaska       0-17 years                   0.000000
             18-64 years                  0.000000

                          Average Pneumonia or Influenza  \
Jurisdiction Age Group
Alabama      0-17 years                         0.000000
             18-64 years                       23.945946
             65+ years                         70.923077
Alaska       0-17 years                         0.000000
             18-64 years                        0.000000

                          Average Pneumonia, Influenza, or COVID-19 Deaths
Jurisdiction Age Group
Alabama      0-17 years                                           0.000000
             18-64 years                                         39.657895
             65+ years                                          122.102564
Alaska       0-17 years                                           0.000000
             18-64 years                                          0.000000

In [9]:
#Group by Jurisdiction and Age Group - sum of remaining columns
age_grp2_df=clean_df2.groupby(['Jurisdiction', 'Age Group']).sum()
age_grp2_df.head(5)

                          MMWRyear  MMWRweek  COVID-19 Deaths  Total Deaths  \
Jurisdiction Age Group
Alabama      0-17 years      78780       936              0.0         367.0
             18-64 years     78780       936            890.0       12431.0
             65+ years       78780       936           3053.0       31671.0
Alaska       0-17 years      78780       936              0.0           0.0
             18-64 years     78780       936              0.0        1152.0

                          Pneumonia Deaths  Influenza Deaths  \
Jurisdiction Age Group
Alabama      0-17 years                0.0               0.0
             18-64 years             836.0              11.0
             65+ years              2711.0               0.0
Alaska       0-17 years                0.0               0.0
             18-64 years               0.0               0.0

                          Pneumonia or Influenza  \
Jurisdiction Age Group
Alabama      0-17 years                      0.0
             18-64 years                   886.0
             65+ years                    2766.0
Alaska       0-17 years                      0.0
             18-64 years                     0.0

                          Pneumonia, Influenza, or COVID-19 Deaths
Jurisdiction Age Group
Alabama      0-17 years                                        0.0
             18-64 years                                    1507.0
             65+ years                                      4762.0
Alaska       0-17 years                                        0.0
             18-64 years                                       0.0

In [10]:
#Group by Jurisdiction  - mean of remaining columns
age_grp3_df=clean_df2.groupby(['Jurisdiction']).mean()
age_grp3_df=age_grp3_df.rename(
    columns= {'COVID-19 Deaths':"Average COVID-19 Deaths",
              'Total Deaths':"Average Total Deaths",
              "Pneumonia Deaths":"Average Pneumonia Deaths",
              "Influenza Deaths":"Average Influenza Deaths",
              "Pneumonia or Influenza":"Average Pneumonia or Influenza",
              "Pneumonia, Influenza, or COVID-19 Deaths":"Average Pneumonia, Influenza, or COVID-19 Deaths"         
            })
age_grp3_df.head(5)

,MMWRyear,MMWRweek,Average COVID-19 Deaths,Average Total Deaths,Average Pneumonia Deaths,Average Influenza Deaths,Average Pneumonia or Influenza,"Average Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,2020,24,34.893805,419.518868,32.245455,0.129412,33.200000,56.990909
Alaska,2020,24,0.000000,39.185185,0.000000,0.000000,0.000000,0.000000
Arizona,2020,24,47.596330,470.324561,51.831776,0.137931,53.819048,76.057692
Arkansas,2020,24,16.150000,289.100000,21.650485,0.111111,22.533981,30.523364
California,2020,24,156.775701,1896.655172,234.821053,5.802198,243.319149,325.290323

In [11]:
#Group by Jurisdiction  - sum of remaining columns
age_grp4_df=clean_df2.groupby(['Jurisdiction']).sum()
age_grp4_df.head(5)

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,236340,2808,3943.0,44469.0,3547.0,11.0,3652.0,6269.0
Alaska,236340,2808,0.0,3174.0,0.0,0.0,0.0,0.0
Arizona,236340,2808,5188.0,53617.0,5546.0,12.0,5651.0,7910.0
Arkansas,236340,2808,1615.0,26019.0,2230.0,10.0,2321.0,3266.0
California,236340,2808,16775.0,220012.0,22308.0,528.0,22872.0,30252.0

In [12]:
#Group by Age Group  - mean of remaining columns
age_grp5_df=clean_df2.groupby(['Jurisdiction']).mean()
age_grp5_df=age_grp5_df.rename(
    columns= {'COVID-19 Deaths':"Average COVID-19 Deaths",
              'Total Deaths':"Average Total Deaths",
              "Pneumonia Deaths":"Average Pneumonia Deaths",
              "Influenza Deaths":"Average Influenza Deaths",
              "Pneumonia or Influenza":"Average Pneumonia or Influenza",
              "Pneumonia, Influenza, or COVID-19 Deaths":"Average Pneumonia, Influenza, or COVID-19 Deaths"         
            })
age_grp5_df.head(5)

,MMWRyear,MMWRweek,Average COVID-19 Deaths,Average Total Deaths,Average Pneumonia Deaths,Average Influenza Deaths,Average Pneumonia or Influenza,"Average Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,2020,24,34.893805,419.518868,32.245455,0.129412,33.200000,56.990909
Alaska,2020,24,0.000000,39.185185,0.000000,0.000000,0.000000,0.000000
Arizona,2020,24,47.596330,470.324561,51.831776,0.137931,53.819048,76.057692
Arkansas,2020,24,16.150000,289.100000,21.650485,0.111111,22.533981,30.523364
California,2020,24,156.775701,1896.655172,234.821053,5.802198,243.319149,325.290323

In [13]:

#Group by Age Group  - sum of remaining columns
age_grp6_df=clean_df2.groupby(['Jurisdiction']).sum()
age_grp6_df.tail(5)

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Virginia,236340,2808,3501.0,56406.0,3589.0,25.0,3700.0,5906.0
Washington,236340,2808,1954.0,44531.0,3202.0,20.0,3333.0,4336.0
West Virginia,236340,2808,269.0,15504.0,920.0,0.0,1002.0,1246.0
Wisconsin,236340,2808,1623.0,42217.0,2070.0,70.0,2241.0,3615.0
Wyoming,236340,2808,0.0,3909.0,45.0,0.0,57.0,71.0

In [14]:
Influenza_table1 = age_grp6_df[["COVID-19 Deaths","Total Deaths","Pneumonia or Influenza"]]
Influenza_table1 = Influenza_table1.rename(columns={"COVID-19 Deaths":"COVID-19_Deaths","Total Deaths": "Total_Deaths","Pneumonia or Influenza": "Pneumonia_Influenza_Deaths"})
Influenza_table1

,COVID-19_Deaths,Total_Deaths,Pneumonia_Influenza_Deaths
Jurisdiction,,,
Alabama,3943.0,44469.0,3652.0
Alaska,0.0,3174.0,0.0
Arizona,5188.0,53617.0,5651.0
Arkansas,1615.0,26019.0,2321.0
California,16775.0,220012.0,22872.0
Colorado,1951.0,32230.0,2521.0
Connecticut,4307.0,25007.0,1963.0
Delaware,464.0,7549.0,360.0
District of Columbia,578.0,4392.0,613.0
Florida,15841.0,174349.0,18137.0
Georgia,6726.0,70871.0,6400.0
Hawaii,144.0,8660.0,413.0
Idaho,434.0,11197.0,470.0
Illinois,8703.0,92098.0,9286.0
Indiana,3930.0,52643.0,4881.0
Iowa,1556.0,23875.0,1623.0
Kansas,875.0,21026.0,1357.0
Kentucky,1344.0,36706.0,3373.0
Louisiana,5189.0,39472.0,4089.0
Maine,54.0,11215.0,589.0
Maryland,4403.0,43157.0,4261.0
Massachusetts,8038.0,50268.0,5738.0
Michigan,6582.0,82475.0,7530.0
Minnesota,2260.0,35465.0,2668.0
Mississippi,3070.0,28073.0,3397.0
Missouri,2727.0,48801.0,3388.0
Montana,170.0,7820.0,319.0
Nebraska,543.0,12804.0,844.0
Nevada,1508.0,20786.0,2326.0
New Hampshire,403.0,9810.0,480.0
New Jersey,14264.0,71265.0,10377.0
New Mexico,706.0,15026.0,1038.0
New York,32914.0,154918.0,24202.0
New York City,0.0,0.0,0.0
North Carolina,2716.0,60402.0,4490.0
North Dakota,188.0,5036.0,225.0
Ohio,4939.0,94223.0,6536.0
Oklahoma,1429.0,30000.0,2934.0
Oregon,511.0,27534.0,1150.0
Pennsylvania,8775.0,107079.0,8079.0
Rhode Island,959.0,8039.0,587.0
South Carolina,3608.0,43177.0,3813.0
South Dakota,158.0,6055.0,227.0
Tennessee,2709.0,57441.0,4969.0
Texas,17457.0,170391.0,18675.0
Utah,385.0,14777.0,713.0
Vermont,31.0,4585.0,71.0
Virginia,3501.0,56406.0,3700.0
Washington,1954.0,44531.0,3333.0
West Virginia,269.0,15504.0,1002.0
Wisconsin,1623.0,42217.0,2241.0
Wyoming,0.0,3909.0,57.0

In [15]:
###### Collect lat and long
#1 - US Cities Longitudes and Latitudes

file_path2 = os.path.join('..', 'References', 'US Cities Long_Lat.csv')

# Import the US Cities Long_Lat.csv file as a DataFrame
uslat_lon_df=pd.read_csv(file_path2)

uslat_lon_df.head()

  STATE   LATITUDE   LONGITUDE        NAME
0    AK  63.588753 -154.493062      Alaska
1    AL  32.318231  -86.902298     Alabama
2    AR  35.201050  -91.831833    Arkansas
3    AZ  34.048928 -111.093731     Arizona
4    CA  36.778261 -119.417932  California

In [16]:
####Append Longitude and Latitude to the Influenza_table
# Merge this group df with the original dataframe to get the tumor volume at the last timepoint

## df.reset_index(level=['tick', 'obs'])

Influenza_table2= Influenza_table1.reset_index(level='Jurisdiction', inplace=False)

Influenza_table2 = Influenza_table2.merge(uslat_lon_df, how='inner', 
                                        left_on=["Jurisdiction"], 
                                        right_on =["NAME"],
                                        suffixes=('', '_y')
                                       )

Influenza_table =Influenza_table2.set_index('Jurisdiction', inplace=False)
Influenza_table

,COVID-19_Deaths,Total_Deaths,Pneumonia_Influenza_Deaths,STATE,LATITUDE,LONGITUDE,NAME
Jurisdiction,,,,,,,
Alabama,3943.0,44469.0,3652.0,AL,32.318231,-86.902298,Alabama
Alaska,0.0,3174.0,0.0,AK,63.588753,-154.493062,Alaska
Arizona,5188.0,53617.0,5651.0,AZ,34.048928,-111.093731,Arizona
Arkansas,1615.0,26019.0,2321.0,AR,35.201050,-91.831833,Arkansas
California,16775.0,220012.0,22872.0,CA,36.778261,-119.417932,California
Colorado,1951.0,32230.0,2521.0,CO,39.550051,-105.782067,Colorado
Connecticut,4307.0,25007.0,1963.0,CT,41.603221,-73.087749,Connecticut
Delaware,464.0,7549.0,360.0,DE,38.910832,-75.527670,Delaware
District of Columbia,578.0,4392.0,613.0,DC,38.905985,-77.033418,District of Columbia
Florida,15841.0,174349.0,18137.0,FL,27.664827,-81.515754,Florida
Georgia,6726.0,70871.0,6400.0,GA,32.157435,-82.907123,Georgia
Hawaii,144.0,8660.0,413.0,HI,19.898682,-155.665857,Hawaii
Idaho,434.0,11197.0,470.0,ID,44.068202,-114.742041,Idaho
Illinois,8703.0,92098.0,9286.0,IL,40.633125,-89.398528,Illinois
Indiana,3930.0,52643.0,4881.0,IN,40.551217,-85.602364,Indiana
Iowa,1556.0,23875.0,1623.0,IA,41.878003,-93.097702,Iowa
Kansas,875.0,21026.0,1357.0,KS,39.011902,-98.484246,Kansas
Kentucky,1344.0,36706.0,3373.0,KY,37.839333,-84.270018,Kentucky
Louisiana,5189.0,39472.0,4089.0,LA,31.244823,-92.145024,Louisiana
Maine,54.0,11215.0,589.0,ME,45.253783,-69.445469,Maine
Maryland,4403.0,43157.0,4261.0,MD,39.045755,-76.641271,Maryland
Massachusetts,8038.0,50268.0,5738.0,MA,42.407211,-71.382437,Massachusetts
Michigan,6582.0,82475.0,7530.0,MI,44.314844,-85.602364,Michigan
Minnesota,2260.0,35465.0,2668.0,MN,46.729553,-94.685900,Minnesota
Mississippi,3070.0,28073.0,3397.0,MS,32.354668,-89.398528,Mississippi
Missouri,2727.0,48801.0,3388.0,MO,37.964253,-91.831833,Missouri
Montana,170.0,7820.0,319.0,MT,46.879682,-110.362566,Montana
Nebraska,543.0,12804.0,844.0,NE,41.492537,-99.901813,Nebraska
Nevada,1508.0,20786.0,2326.0,NV,38.802610,-116.419389,Nevada
New Hampshire,403.0,9810.0,480.0,NH,43.193852,-71.572395,New Hampshire
New Jersey,14264.0,71265.0,10377.0,NJ,40.058324,-74.405661,New Jersey
New Mexico,706.0,15026.0,1038.0,NM,34.972730,-105.032363,New Mexico
New York,32914.0,154918.0,24202.0,NY,43.299428,-74.217933,New York
North Carolina,2716.0,60402.0,4490.0,NC,35.759573,-79.019300,North Carolina
North Dakota,188.0,5036.0,225.0,ND,47.551493,-101.002012,North Dakota
Ohio,4939.0,94223.0,6536.0,OH,40.417287,-82.907123,Ohio
Oklahoma,1429.0,30000.0,2934.0,OK,35.007752,-97.092877,Oklahoma
Oregon,511.0,27534.0,1150.0,OR,43.804133,-120.554201,Oregon
Pennsylvania,8775.0,107079.0,8079.0,PA,41.203322,-77.194525,Pennsylvania
Rhode Island,959.0,8039.0,587.0,RI,41.580095,-71.477429,Rhode Island
South Carolina,3608.0,43177.0,3813.0,SC,33.836081,-81.163725,South Carolina
South Dakota,158.0,6055.0,227.0,SD,43.969515,-99.901813,South Dakota
Tennessee,2709.0,57441.0,4969.0,TN,35.517491,-86.580447,Tennessee
Texas,17457.0,170391.0,18675.0,TX,31.968599,-99.901813,Texas
Utah,385.0,14777.0,713.0,UT,39.320980,-111.093731,Utah
Vermont,31.0,4585.0,71.0,VT,44.558803,-72.577841,Vermont
Virginia,3501.0,56406.0,3700.0,VA,37.431573,-78.656894,Virginia
Washington,1954.0,44531.0,3333.0,WA,47.751074,-120.740139,Washington
West Virginia,269.0,15504.0,1002.0,WV,38.597626,-80.454903,West Virginia
Wisconsin,1623.0,42217.0,2241.0,WI,43.784440,-88.787868,Wisconsin
Wyoming,0.0,3909.0,57.0,WY,43.075968,-107.290284,Wyoming